"""
Django settings for openlexicon project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from openlexicon.prod_base_settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
LOG_LEVEL = log_level
DEBUG = debug
PRODUCTION = production

#SITE_URL = "openlexicon.org"
#SITE_URL = "5.39.73.115"
SITE_NAME = "OpenLexicon"
SITE_URL = "lexique.org"
CSRF_TRUSTED_ORIGINS = ["http://www.lexique.org", "http://*lexique.org"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'openlexiconApp.apps.OpenlexiconappConfig',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'openlexicon.urls'

INTERNAL_IPS = ["127.0.0.1", SITE_URL]

# NOTE : does not work if several workers on /etc/systemd/system/gunicorn.service
# NOTE : if we put large data in cache (like a list of integers), it really really slows the rendering !!
def custom_show_toolbar(request):
    return show_toolbar

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': custom_show_toolbar,
    'RENDER_PANELS': None,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'openlexicon' / 'templates',
            BASE_DIR / 'openlexiconApp' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

WSGI_APPLICATION = 'openlexicon.wsgi.application'

##############################
########## Security ##########
##############################

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# To remove MIME type warning from firefox
# https://stackoverflow.com/questions/11811256/how-to-set-content-type-of-javascript-files-in-django
if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

if DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "lexique.org", "www.lexique.org"]
else:
    ALLOWED_HOSTS = ["localhost", "0.0.0.0", SITE_URL, "www." + SITE_URL]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
'''CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SAMESITE = None
if not PRODUCTION:
    SECURE_SSL_REDIRECT = False
else:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    BASE_URL = "https://"+SITE_URL
'''
##############################
########## Database ##########
##############################
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if not PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'django_openlexicon',
            'USER': 'postgres',
            'PASSWORD': db_pass,
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
        	    'NAME': 'django_openlexicon',
                'USER': 'django_openlexicon',
                'PASSWORD': db_pass,
                'HOST': 'localhost',
                'PORT': '',
            }
        }

##############################
########### Cache ############
##############################
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'
    }
}

##############################
########## Password ##########
##############################
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

##############################
########### Media ############
##############################

USE_X_FORWARDED_HOST = True
if not PRODUCTION:
    FORCE_SCRIPT_NAME = ""
else:
    FORCE_SCRIPT_NAME = '/django'
MEDIA_URL = os.path.join(FORCE_SCRIPT_NAME, 'media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Toolbar options: https://ckeditor.com/latest/samples/old/toolbar/toolbar.html
CKEDITOR_5_CONFIGS = {
    'default': {
        'filebrowserBrowseUrl': '', # remove browse server button
        "removePlugins": "exportpdf,easyimage,cloudservices,elementspath",
        "resize_enabled": False,
        'width': '100%',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format', 'Font', 'FontSize'],
            ['Redo', 'Undo'],
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'TextColor']
        ]
    }
}

##############################
#### Internationalization ####
##############################
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

##############################
########### Static ###########
##############################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = os.path.join(FORCE_SCRIPT_NAME, 'static/')
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'openlexicon', 'static')
]

CONTACT_MAIL = "contact@lexique.org"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

##############################
########### Email ############
##############################
# FOR TESTING
'''if not PRODUCTION:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = str(os.path.join(BASE_DIR, 'sent_emails'))
else:
    # FOR REAL MAILS
    EMAIL_USE_TLS = True
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = "lexique.org"
    EMAIL_HOST_PASSWORD = passmail
    EMAIL_HOST_USER = 'zebulon'
    EMAIL_PORT = 587
    #https://stackoverflow.com/questions/26333009/how-do-you-configure-django-to-send-mail-through-postfix
    DEFAULT_FROM_EMAIL = "Contact LEXIQUE <contact@lexique.org>"
    EMAIL_SUBJECT_PREFIX = "[LEXIQUE]"
'''
##############################
########### Models ###########
##############################

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = os.path.join(FORCE_SCRIPT_NAME, "accounts", "login")
LOGIN_REDIRECT_URL = os.path.join(FORCE_SCRIPT_NAME, "openlexicon")
LOGOUT_REDIRECT_URL = os.path.join(FORCE_SCRIPT_NAME, "openlexicon")

DEFAULT_DB = "Lexique3"
